/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Portfolio;
import io.swagger.model.Project;

@Api(value = "portfolio", description = "the portfolio API")
@RequestMapping("/portfolio")
public interface PortfolioApi {

    @ApiOperation(value = "registers a portfolio", nickname = "registerPortfolio", notes = "Registers a new portfolio", tags={ "admins", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Successful registration"),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "an existing portfolio already exists") })
    @RequestMapping(value = "/",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Portfolio> registerPortfolio(@ApiParam(value = "Portfolio to register"  )  @Valid @RequestBody Portfolio portfolio);


    @ApiOperation(value = "unregisters a portfolio", nickname = "unregisterPortfolio", notes = "Unregisters an existent portfolio", tags = {"admins", })
    @ApiResponses(value = {
            @ApiResponse(code = 202, message = "Portfolio marked for disabling"),
            @ApiResponse(code = 204, message = "Portfolio unregistered")})
    @RequestMapping(value = "/{portfolioId}", produces = {"application/json"}, method = RequestMethod.DELETE)
    ResponseEntity<Void> unregisterPortfolio(@ApiParam(value = "portfolio id to unregister", required = true) @PathVariable("portfolioId") String portfolioId);

    @ApiOperation(value = "searches all portfolios", nickname = "searchAllPortfolios", notes = "Searches all portfolios", response = Portfolio.class, responseContainer = "List", tags={ "admins","investors","projectOwners", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns all portfolios", response = Portfolio.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "not portfolios registered") })
    @RequestMapping(value = "/",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Portfolio>> searchAllPortfolios();


    @ApiOperation(value = "searches portfolio", nickname = "searchPortfolio", notes = "given an ID it searches portfolio", response = Object.class, tags={ "admins","investors","projectOwners", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = Object.class),
        @ApiResponse(code = 400, message = "portfolio not found") })
    @RequestMapping(value = "/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Portfolio> searchPortfolio(@ApiParam(value = "id portfolio to find",required=true) @PathVariable("portfolioId") Integer portfolioId);

    @ApiOperation(value = "search a project list given a portfolio", nickname = "listProjects", notes = "Given a valid portfolio Id, returns all its projects", response = Object.class, tags={ "admins","investors","projectOwners", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Return result", response = Object.class),
            @ApiResponse(code = 400, message = "incorrect parameter") })
    @RequestMapping(value = "/{id}/projects",
            produces = { "application/json" },
            method = RequestMethod.GET)
    @ResponseBody
    List<Project> listProjects(@ApiParam(value = "portfolio id search project",required=true) @PathVariable("id") Integer id);
}
